### ISSUE TITLE
ImportError: No module named compressor

### ISSUE THREAD

**Issue by shikolay** [APSL/puput#50]
puput should have django_compressor as dependency 
Because after fresh installation python manage.py migrate gives compressor import errors

**Comment by marctc** [comment]
Is already changed in setup.py. I have to upload a new version to PyPI.

**Comment by marctc** [comment]
Fixed on version 0.6

**Comment by hnjogu** [comment]
experiencing the same problem
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named compressorme problem

**Comment by junhao1996** [comment]
you can use pip install django_compressor

**Comment by hnjogu** [comment]
yah thanks it have worked

**Comment by Anurag-117** [comment]
> you can use pip install django_compressor

I have already did that. `pip list` showss django-compressor is installed. But it still isn't working.

**Comment by jestinmwilson** [comment]
pip install django_compressor  already installed but it's not working
